Traceback (most recent call last):
  File "/Users/crovella/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/crovella/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/crovella/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/crovella/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/crovella/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/crovella/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/crovella/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/crovella/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('Top terms per cluster:')
asc_order_centroids = kmeans.cluster_centers_.argsort()#[:, ::-1]
order_centroids = asc_order_centroids[:,::-1]
terms = vectorizer.get_feature_names()
for i in range(k):
    print(f'Cluster {i}:')
    for ind in order_centroids[i, :10]:
        print(f' {terms[ind]}')
    print('')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[31], line 4[0m
[1;32m      2[0m asc_order_centroids [38;5;241m=[39m kmeans[38;5;241m.[39mcluster_centers_[38;5;241m.[39margsort()[38;5;66;03m#[:, ::-1][39;00m
[1;32m      3[0m order_centroids [38;5;241m=[39m asc_order_centroids[:,::[38;5;241m-[39m[38;5;241m1[39m]
[0;32m----> 4[0m terms [38;5;241m=[39m [43mvectorizer[49m[38;5;241;43m.[39;49m[43mget_feature_names[49m()
[1;32m      5[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m(k):
[1;32m      6[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mCluster [39m[38;5;132;01m{[39;00mi[38;5;132;01m}[39;00m[38;5;124m:[39m[38;5;124m'[39m)

[0;31mAttributeError[0m: 'TfidfVectorizer' object has no attribute 'get_feature_names'
AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names'

